language: node_js
node_js:
- '6'
before_install:
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "Y7nslUWXTHVyM/Arw6Yce75QjjiM9GXURK7Q8lWCZc8hWqugfotkhe1lAwKyUaNi08Yv53Z3xPYmukPMh61688t4Bg6sgHds6t/ojDkl7zm51XJz1sySH4Yion0caV6ig/f6Ofn4z9qh8FRig+q27jS+DE1+VBPivXmf6S+iEqOMcae9ND87VmtLhJdlspaEWnEvD7nVBdBxFHdvFPdprU/cF8TblKrSaDGrPPNwnD8uE5Qsn8xqwmv5bieg6yk1Bi7sS8+xu/C1E40A8Uj6ATJudE5KVB9eG0VvzvFb/hngfmt7DjL92Eb/KCC8qPCLZ2wFc3YR07MyzE1T/scLXlwjC1GLT0ncOy8Iq8FV+qgPKPz0jDBy6xq/3VgLi2DxGchoDGeS3NaBI0UyWkX+GDXTEaDhyqt+YpO5Ej5eAnyZLLALVKi+BP5TcK9qq36pGERLkOdoO87ke71JvoN+zUuyED23q1cbfWSYbBPvovFYgPY2E8BRvH/qYgI1gl7JqlhA9WwAL5Vo7JJ369L0yKiLUo8KmlaqlFmI37ycFKN177U6ut7c24bw7bUbGCKNJORPZnQSvWnkiOQF6YNM99IYd+4dzvJKyNNWRcED05ZbKD39wmee6IQmWbGCilE/29IW9Eg/Xd2AMioaz2IxJOqaCCMrDY9vVNGkuuoQ5J0="