language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- npm run test-karma
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js

env:
  secure: "TdlkWDL98eMUpbdcL6tE2VfrGn3qUtid/mNkFXWV887HZHB74p9iQh/C2yzsnhjlXiHAWANBrizEepjYEZVWtCIvxPH7Ep4qdm8/PIZ9WKZWZlOj+chIymD6K7QHd5hyPdRyx78/tHmq9BwlEEMLEfREEnaExW/zlJXBgLgGbCY1a2sr1cPHxW9xmAvjZoqy1uK8+OiwC8XdK3icq4fq08CglPH0iXesgfp4uqb6yqNs7nJARo0vxDAuRbT5MNAeFTGSyS1rMXpEwX+No0bEtj7OnM97DQ/UabYz4fq2jMprIuPveUC1+dUl6Z79frHh4QHAndKtiw1LSQt0huyJdqe0NmKgOD8I8aEoOdUjKV3DAkMh4XLAoZdcatCZZAkrWvZpbyhw8CFoyFMAfSqaaD3PfI+sXiHfq/2dbMy7I4FWynEnSBAiEx3zDVoE6aFgXzBpmUgs6d8ecatMu2DXibzTultLEVC7SvBg356iM3KkC7GYmiYIOlq+L5QDkgD36yP17HGZTNDzs3GxEWGroOrzl8JhzMeSg6XHyJaV+86nL+kQ+vkTcVv6xZLredg0GZdOLQ4+7DiCmqRdF6PSWkTxiWwSyYfbKSWPaSBCp7zkyhXYoakHzH4hWeqMp3EpEHMJB2ddso06ghaHobgmayICFubs/1SeZvV4O7eWxJ4="
