language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- npm run test-karma
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js

env:
  secure: "EhpTHsR0hwNsOOVm8dj8TvcHox/tBGtv1kMfrdHg2EclVzXGumQYTkvH4XdH7Rx7TRLRCtNoxqf6h578p482lAeH9qp9JUt3/Rg1WInADiKjXkuYx/9pLog/oE+KJyvQUP5tiYCj9w5/2j7/Zk8mfktuvomxUtxsIzUlapRT1UL70YqIkPU6bJ23OZdL5V8P78UB3ax+W8a5t7Y810ZUPWZN3DY1GNjiQzDX9hkiqCWwVCFOKUADNBSSYQd8NKr9fKJ9UYgtFWzL0Ajxq4Jnt33Aq2T5NsCsQR36ar/gus39TSHegPcpNVepZskP1lSyc9egcWKMNnGbNsu9ofPewGHC4RXKkjYWSunT5y2ICio8o0xTA2h4RXweCwcRor0d0zuHZZqJZJL/HvfT2uYsKxt4nWnm7yAVhUw1TKV0Cjr20jolZKocQDoDGxLoIjJvbNqVXA/YP89krH6nqk7qryz0WCi5/AgIYb8m1mHj1peRux2sBAVDE8ZeZZOcyroWyHf4v7kdMT1AAs3+pF3+5x2aDk/tu6kZaFnS/fTmXt4FkhxT7/p7kBn7arCquaG1v6AWTO4uDGtVCSrq9OWVc4TiSNVtwBMO3gKWTNLvW2hqnGO5RSHdO+eXxFxpQs4dblwsgr2wkqtKhlvI1oy7IxjdxDaGNhNCRxN34xaajDU="
