language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- npm run test-karma
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "o5EMuYsSFEigQiEjZx4b/k7ZmXYXqrcku4v/mPah+24X/0G/vhnN5SmP74wOAvtIW8eMXlXAaFBGVtOx+tWHJVRnTpfFIfZpEpF8QuPJcpRqYw1MhzKGZMNoW6mM2/i93G9e19G4+b+DUh/d7XC6gZOWtHxXDYkDTr3bx99DwfX/iPYrn7gc4QLVx/IjIE5qBXy8V8+AlDpJ4cbMNIZ9Nilvrjft1vt/3FZaB392X3C3IPr/5VGbUM1WAGT+FGeDkNsYKlzDxBAGkKr4SgkP1XmNNmRAkxzE1dImQ6HavyamTB/dQD4FVii0V1nyoxD2v7jbIjYTYmrVXIZN0D9ziViZxT76hfh/dgIGv0cqW9PNfG9Yel4g6bbWnYQPyla0ZP530TTQB33+RR34a9L1OiD+Z8GEHeGCWz6ixkDboF3/MB8P9u5jLpoHCA15X1+78vGPRtYzJmzvJpJ8Vfy6IrwyDOrWc/sdUXT8QDpDU0MLvjTS5Xek8NrD3eR4gkzS0FMdksWcEZZD50snwsEuGZtBYh1QKHYn8zLM3Oo+GRVhARAgIYALAYcef6ihctLlNPOhL9uJmz7a8kkKaY/oQO9Y9oGJwdpm+B0Y0MqbCRx149ETUxtdcdZBBelTqD+ROn2bX+joecAosi/L83vIFjH6NKfuBCQtF0esjURr5BA="
